### ISSUE TITLE
How to use `napari viewer`?

### ISSUE THREAD

**Issue by LucaMarconato** [scverse/napari-spatialdata#101]
@berombau I have tried using `napari viewer path/to/data.zarr` as described in the docs https://github.com/scverse/napari-spatialdata/blob/6d4cc8dc4f27b676ef50bd4d697e00d5d765db21/docs/cli.md (btw, there were some mistakes, I have corrected them in this commit https://github.com/scverse/napari-spatialdata/commit/6d4cc8dc4f27b676ef50bd4d697e00d5d765db21), but I get this error:

```
(ome) macbook@MBP-2021 spatialdata-sandbox % napari viewer curio_io/data.zarr                    
Traceback (most recent call last):
  File "/Users/macbook/miniconda3/envs/ome/bin/napari", line 8, in <module>
    sys.exit(main())
  File "/Users/macbook/miniconda3/envs/ome/lib/python3.10/site-packages/napari/__main__.py", line 561, in main
    _run()
  File "/Users/macbook/miniconda3/envs/ome/lib/python3.10/site-packages/napari/__main__.py", line 341, in _run
    viewer._window._qt_viewer._qt_open(
  File "/Users/macbook/miniconda3/envs/ome/lib/python3.10/site-packages/napari/_qt/qt_viewer.py", line 830, in _qt_open
    self.viewer.open(
  File "/Users/macbook/miniconda3/envs/ome/lib/python3.10/site-packages/napari/components/viewer_model.py", line 1024, in open
    layers = self._open_or_raise_error(
  File "/Users/macbook/miniconda3/envs/ome/lib/python3.10/site-packages/napari/components/viewer_model.py", line 1094, in _open_or_raise_error
    raise NoAvailableReaderError(
napari.errors.reader_errors.NoAvailableReaderError: No plugin found capable of reading viewer.
```

Do I need to manually register the plugin? Do you know how to fix this?

**Comment by LucaMarconato** [comment]
Thanks @berombau, I wrongly made that change. Could you please update the docs in the linked PR? Thanks
